import "./sidebar-plugin";
import PluginAccordion from "@flexilla/alpine-accordion";
import PluginRangeIndicator from "@flexilla/alpine-range-indicator";
import PluginAutoResizeArea from "@flexilla/alpine-autoresize-area";
import PluginOffcanvas from "@flexilla/alpine-offcanvas";
import PluginPopover from "@flexilla/alpine-popover";
import PluginTooltip from "@flexilla/alpine-tooltip";
import PluginPinInput from "@flexilla/alpine-pin-input";
import PluginNavbar from "@flexilla/alpine-navbar";
import AlpineModal from "@flexilla/alpine-modal";
import AlpineTabs from "@flexilla/alpine-tabs";
import PluginDropdown from "@flexilla/alpine-dropdown";
import PluginModal from "@flexilla/alpine-modal";

Alpine.plugin(PluginAccordion);
Alpine.plugin(PluginModal);
Alpine.plugin(PluginDropdown);
Alpine.plugin(AlpineModal);
Alpine.plugin(AlpineTabs);
Alpine.plugin(PluginRangeIndicator);
Alpine.plugin(PluginAutoResizeArea);
Alpine.plugin(PluginOffcanvas);
Alpine.plugin(PluginPopover);
Alpine.plugin(PluginTooltip);
Alpine.plugin(PluginPinInput);
Alpine.plugin(PluginNavbar);
