<?php

return [
    [
        'label' => 'Getting Started',
        'items' => [
            [
                'title' => 'Introduction',
                'path' => '/docs/introduction',
                'description' => 'Comprehensive overview of Flexiwind Laravel, a modern Blade and Livewire UI toolkit.',
                'keywords' => 'Laravel UI, Blade Components, Livewire UI, Tailwind CSS v4, Flexiwind Intro',
                'seoDescription' => 'Learn how to get started with Flexiwind Laravel, a modern collection of Laravel Blade and Livewire UI components built with TailwindCSS.',
            ],
            [
                'title' => 'Installation',
                'path' => '/docs/installation',
                'description' => 'Guide on installing Flexiwind via Composer and configuring Tailwind CSS.',
                'keywords' => 'Installation, Composer, Laravel Setup, Tailwind Config, UI Package',
                'seoDescription' => 'Step-by-step guide on how to install and set up Flexiwind in your Laravel project.',
            ],
            [
                'title' => 'Theming',
                'path' => '/docs/theme',
                'description' => 'Customize the look and feel using CSS variables and Tailwind configuration.',
                'keywords' => 'Theming, Customization, Design Tokens, Colors, Branding',
                'seoDescription' => 'Learn how to customize and theme your Flexiwind components to match your project\'s design system.',
            ],
            [
                'title' => 'Dark Mode',
                'path' => '/docs/dark-mode',
                'description' => 'Implementing and toggling dark mode support in your Laravel application.',
                'keywords' => 'Dark Mode, Night Mode, Color Schemes, Appearance, Tailwind Dark',
                'seoDescription' => 'Learn how to implement and customize dark mode for your Flexiwind Laravel components.',
            ],
            [
                'title' => 'Buttons utilities',
                'path' => '/docs/theme/buttons',
                'description' => 'Configuration of global button styles, variants, and size scales.',
                'keywords' => 'Button Styles, Button Variants, Action UI, Design System',
                'seoDescription' => 'Explore Flexiwind\'s button utilities and learn how to create custom button styles and variants.',
            ],
            [
                'title' => 'UI utilities',
                'path' => '/docs/theme/utilities',
                'description' => 'Helper classes and Blade directives to speed up your UI development.',
                'keywords' => 'Utilities, Helpers, Blade Directives, Spacing, Layout Helpers',
                'seoDescription' => 'Discover Flexiwind\'s utility classes for building consistent and responsive user interfaces.',
            ],
        ],
    ],
    [
        'label' => 'Layout & Structure',
        'items' => [
            [
                'title' => 'Container',
                'path' => '#',
                'description' => 'Max-width wrapper for centering and constraining content.',
                'keywords' => 'container, wrapper, layout, responsive',
                'state' => 'draft',
                'seoDescription' => 'Learn about Flexiwind\'s container component for consistent layout management.',
            ],
            [
                'title' => 'Grid',
                'path' => '#',
                'description' => 'Powerful grid system for building complex responsive layouts.',
                'keywords' => 'grid, flexbox, columns, rows, spacing',
                'state' => 'draft',
                'seoDescription' => 'Create responsive layouts with Flexiwind\'s grid system.',
            ],
            [
                'title' => 'Navbar',
                'path' => '#',
                'description' => 'Header navigation component with support for branding and menus.',
                'keywords' => 'navbar, header, navigation, menu, top-bar',
                'state' => 'draft',
                'seoDescription' => 'Responsive navigation bar component for Laravel applications.',
            ],
            [
                'title' => 'Sidebar',
                'path' => '#',
                'description' => 'Collapsible vertical navigation container for application dashboards.',
                'keywords' => 'sidebar, navigation, aside, drawer',
                'state' => 'draft',
                'seoDescription' => 'Create responsive sidebars with Flexiwind\'s layout components.',
            ],
            [
                'title' => 'Card',
                'path' => '/components/card',
                'description' => 'Organized content container with header, body, and footer sections.',
                'keywords' => 'card, box, panel, container, dashboard ui',
                'seoDescription' => 'Display content in organized cards with Flexiwind\'s card component.',
            ],
            [
                'title' => 'Divider',
                'path' => '/components/divider',
                'description' => 'Visual separator for grouping or distinguishing content blocks.',
                'keywords' => 'divider, separator, hr, line, spacing',
                'seoDescription' => 'Add visual separation between content with Flexiwind\'s divider component.',
            ],
        ],
    ],
    [
        'label' => 'Forms & Inputs',
        'items' => [
            [
                'title' => 'Input',
                'path' => '/components/input',
                'description' => 'Enhanced text input field with support for icons and validation.',
                'keywords' => 'input, form field, text input, validation',
                'seoDescription' => 'Build form inputs with various styles using Flexiwind\'s input component.',
            ],
            [
                'title' => 'Text Area',
                'path' => '/components/text-area',
                'description' => 'Multi-line text input for longer user descriptions or notes.',
                'keywords' => 'textarea, multi-line, form input, notes',
                'seoDescription' => 'Add multiline text inputs with Flexiwind\'s text area component.',
            ],
            [
                'title' => 'Select',
                'path' => '/components/select',
                'description' => 'Customizable dropdown for single or multiple selection options.',
                'keywords' => 'select, dropdown, options, picker',
                'seoDescription' => 'Create dropdown selection menus with Flexiwind\'s select component.',
            ],
            [
                'title' => 'Checkbox',
                'path' => '/components/checkbox',
                'description' => 'Standard checkbox input for toggling multiple independent options.',
                'keywords' => 'checkbox, check, form, multi-select',
                'seoDescription' => 'Implement multiple selection controls with Flexiwind\'s checkbox component.',
            ],
            [
                'title' => 'Radio',
                'path' => '/components/radio',
                'description' => 'Input group for choosing a single option from a predefined list.',
                'keywords' => 'radio, selection, form, options',
                'seoDescription' => 'Create single-selection controls with Flexiwind\'s radio component.',
            ],
            [
                'title' => 'Switch',
                'path' => '/components/switch',
                'description' => 'Modern toggle switch for boolean settings and binary choices.',
                'keywords' => 'switch, toggle, boolean, setting',
                'seoDescription' => 'Implement toggle switches with Flexiwind\'s accessible switch component.',
            ],
            [
                'title' => 'Otp /Pin',
                'path' => '/components/otp',
                'description' => 'Segmented input field designed for verification codes and MFA.',
                'keywords' => 'otp, pin code, auth, verification, 2fa',
                'seoDescription' => 'Create OTP input with Flexiwind\'s otp component.',
            ],
            [
                'title' => 'Range',
                'path' => '/components/range',
                'description' => 'Slider component for selecting numeric values within a span.',
                'keywords' => 'range, slider, input, number picker',
                'seoDescription' => 'Implement range selection inputs with Flexiwind\'s range component.',
            ],
        ],
    ],
    [
        'label' => 'Navigation & Actions',
        'items' => [
            [
                'title' => 'Button',
                'path' => '/components/button',
                'description' => 'Versatile action trigger with support for loading states and icons.',
                'keywords' => 'button, click, trigger, cta, action',
                'seoDescription' => 'Create interactive buttons with various styles using Flexiwind\'s button component.',
            ],
            [
                'title' => 'Dropdown',
                'path' => '/components/dropdown',
                'description' => 'Overlay menu for displaying contextual actions or links.',
                'keywords' => 'dropdown, menu, actions, context menu',
                'seoDescription' => 'Create interactive dropdown menus with Flexiwind\'s dropdown component.',
            ],
            [
                'title' => 'Link',
                'path' => '/components/link',
                'description' => 'Anchor component with consistent typography and hover states.',
                'keywords' => 'link, anchor, navigation, href',
                'seoDescription' => 'Create styled links and navigation elements with Flexiwind\'s link component.',
            ],
            [
                'title' => 'Tabs',
                'path' => '/components/tabs',
                'description' => 'Segmented view switcher for organizing content within a page.',
                'keywords' => 'tabs, switch, navigation, view group',
                'seoDescription' => 'Create tabbed interfaces with Flexiwind\'s tabs component.',
            ],
            [
                'title' => 'Breadcrumbs',
                'path' => '/components/breadcrumbs',
                'description' => 'Path-based navigation to help users identify their current location.',
                'keywords' => 'breadcrumbs, path, navigation, hierarchy',
                'seoDescription' => 'Implement navigation breadcrumbs to improve user orientation.',
            ],
            [
                'title' => 'Pagination',
                'path' => '/components/pagination',
                'description' => 'Controls for navigating through split datasets or multiple pages.',
                'keywords' => 'pagination, pages, tables, navigation',
                'seoDescription' => 'Implement page navigation with Flexiwind\'s pagination component.',
            ],
        ],
    ],
    [
        'label' => 'Data & Feedback',
        'items' => [
            [
                'title' => 'Table',
                'path' => '/components/table',
                'description' => 'Data-rich table component with header, row, and cell styling.',
                'keywords' => 'table, datatable, rows, grid data',
                'seoDescription' => 'Display tabular data with Flexiwind\'s table component.',
            ],
            [
                'title' => 'Avatar',
                'path' => '/components/avatar',
                'description' => 'Visual representation of a user with fallback support for initials.',
                'keywords' => 'avatar, profile, user, image',
                'seoDescription' => 'Display user avatars and profile images with Flexiwind\'s avatar component.',
            ],
            [
                'title' => 'Badge',
                'path' => '/components/badge',
                'description' => 'Compact status indicator for counts, labels, or categories.',
                'keywords' => 'badge, tag, pill, status',
                'seoDescription' => 'Add status indicators and notifications with Flexiwind\'s badge component.',
            ],
            [
                'title' => 'Alert',
                'path' => '/components/alert',
                'description' => 'Inline notification for conveying success, error, or warning messages.',
                'keywords' => 'alert, notice, feedback, message',
                'seoDescription' => 'Implement user notifications with Flexiwind\'s alert component.',
            ],
            [
                'title' => 'Progress',
                'path' => '/components/progress',
                'description' => 'Linear indicator for showing completion percentage or loading.',
                'keywords' => 'progress bar, loading, status, percent',
                'seoDescription' => 'Show progress and loading states with Flexiwind\'s progress component.',
            ],
            [
                'title' => 'Meter',
                'path' => '/components/meter',
                'description' => 'Graphical representation of a scalar measurement within a known range.',
                'keywords' => 'meter, gauge, measurement, indicator',
                'seoDescription' => 'Display measurements and progress with Flexiwind\'s meter component.',
            ],
            [
                'title' => 'Skeleton',
                'path' => '/components/skeleton',
                'description' => 'Animated placeholder used while content is loading.',
                'keywords' => 'skeleton, loader, ghost, placeholder',
                'seoDescription' => 'Add loading state placeholders with Flexiwind\'s skeleton component.',
            ],
        ],
    ],
    [
        'label' => 'Overlays & Disclosure',
        'items' => [
            [
                'title' => 'Modal',
                'path' => '/components/modal',
                'description' => 'Blocking dialog window for critical interactions or forms.',
                'keywords' => 'modal, dialog, popup, overlay',
                'seoDescription' => 'Create interactive modal dialogs with Flexiwind\'s modal component.',
            ],
            [
                'title' => 'Alert Dialog',
                'path' => '/components/alert-dialog',
                'description' => 'Modal variation used for confirmations and critical warnings.',
                'keywords' => 'confirmation, alert dialog, warning modal',
                'seoDescription' => 'Create interactive alert dialogs using Flexiwind\'s modal dialog component.',
            ],
            [
                'title' => 'Slideover',
                'path' => '/components/slideover',
                'description' => 'Side-panel overlay for secondary navigation or settings.',
                'keywords' => 'slideover, drawer, side-panel, overlay',
                'seoDescription' => 'Create slide-in panels with Flexiwind\'s slideover component.',
            ],
            [
                'title' => 'Popover',
                'path' => '/components/popover',
                'description' => 'Floating container for displaying rich content on click or hover.',
                'keywords' => 'popover, dropdown, tooltip, info-box',
                'seoDescription' => 'Add contextual information with Flexiwind\'s popover component.',
            ],
            [
                'title' => 'Tooltip',
                'path' => '/components/tooltip',
                'description' => 'Small informative popup that appears on element hover.',
                'keywords' => 'tooltip, hint, hover, title',
                'seoDescription' => 'Add helpful tooltips to elements with Flexiwind\'s tooltip component.',
            ],
            [
                'title' => 'Accordion',
                'path' => '/components/accordion',
                'description' => 'Vertically collapsing panels for managing dense content.',
                'keywords' => 'accordion, collapse, disclosure, faq',
                'seoDescription' => 'Learn how to use Flexiwind\'s accordion component to create expandable content sections.',
            ],
            [
                'title' => 'Aspect Ratio',
                'path' => '/components/aspect-ratio',
                'description' => 'Utility component to maintain specific dimensions for images or videos.',
                'keywords' => 'aspect ratio, video, image, responsive box',
                'seoDescription' => 'Maintain consistent image and video aspect ratios with Flexiwind\'s component.',
            ],
            [
                'title' => 'Kbd',
                'path' => '/components/kbd',
                'description' => 'Visual representation of keyboard keys for shortcuts.',
                'keywords' => 'keyboard, kbd, shortcut, command',
                'seoDescription' => 'Display keyboard shortcuts and commands with Flexiwind\'s kbd component.',
            ],
            [
                'title' => 'Callout',
                'path' => '/components/callout',
                'description' => 'Attention-grabbing box for tips, warnings, or notes.',
                'keywords' => 'callout, banner, note, highlight',
                'seoDescription' => 'Implement callout for user with Flexiwind\'s callout component.',
            ],
        ],
    ],
];